context:
  name: meso-forge-mirror
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ..

build:
  number: 0
  script:
    - cargo build --release --locked
    - mkdir -p $PREFIX/bin
    - cp target/release/meso-forge-mirror $PREFIX/bin/  # [unix]
    - copy target\release\meso-forge-mirror.exe %PREFIX%\Scripts\  # [win]

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - pkg-config  # [unix]
    - cmake  # [win]
  host:
    - openssl  # [unix]
  run:
    - openssl  # [unix]

tests:
  - script:
      - meso-forge-mirror --help
      - meso-forge-mirror --version

about:
  homepage: https://github.com/babeloff/meso-forge-mirror
  repository: https://github.com/babeloff/meso-forge-mirror
  documentation: https://github.com/babeloff/meso-forge-mirror/tree/main/docs
  license: GPL-3.0-only
  license_file: LICENSE
  summary: A tool for mirroring conda packages from staging PRs to target repositories
  description: |
    A Rust application for mirroring conda packages from various sources to target
    repositories with full conda ecosystem integration. This tool is particularly
    useful when you want to use packages that are waiting to be included in
    conda-forge but are taking a long time to go through the process.

    Enhanced with Rattler Integration for comprehensive conda package processing,
    validation, and proper repository structure management.

    Key Features:
    - Full conda package validation and metadata extraction
    - Platform-aware organization (linux-64/, osx-64/, noarch/, etc.)
    - Automatic repodata.json generation for conda compatibility
    - Support for Local, S3/MinIO, and prefix.dev repositories
    - Concurrent downloads with configurable parallelism
    - GitHub integration for fetching artifacts from staged recipes
    - Enhanced error handling and comprehensive diagnostics
    - Native Rattler cache integration
    - Integrity verification with MD5 and SHA256 checksums

extra:
  recipe-maintainers:
    - phreed
